app/Http/routes.php
<?php

/* Angular Index */
Route::get('/', function () {
    return view('public');
});
Route::get('/design', function () {
    return redirect('/#/design');
});
Route::get('/development', function () {
    return redirect('/#/development');
});
Route::get('/documentation', function () {
    return redirect('/#/documentation');
});

Route::resource('edit/project', 'EditorProjectController');
Route::resource('edit/skill', 'SkillsController');

Route::resource('api/project', 'ApiProjectController');
Route::resource('api', 'ApiController');
Route::resource('edit', 'EditorController');

/* Redirect to angular view */
Route::resource('/project', 'FolioProjectController');
Route::resource('/cat', 'FolioCategoryController');

Route::auth();

Route::get('/home', 'HomeController@index');

app/Project.php
<?php

namespace Portfolio;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use Illuminate\Database\Eloquent\Model;
use Portfolio\Traits\Skillable;
use Portfolio\ProjectLink;

class Project extends Model
{
    use SluggableTrait;
    use Skillable;
    protected $sluggable = array(
        'build_from' => 'name',
        'save_to' => 'slug',
        'on_update' => true,
    );

    protected $fillable = ['name', 'description', 'project_type_id', 'slug'];

    protected $dates = ['created_at', 'updated_at'];
    /**
     * Broad Categorisation for project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function projectType() {
        return $this->belongsTo('Portfolio\ProjectType');
    }
    /**
     * Images attached to this project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function images() {
        return $this->hasMany('Portfolio\ProjectImage');
    }
    /**
     * Returns a multidimensional array of 
     * image titles, captions and urls.
     * @return array
     */
    public function getImgArrayAttribute() {
        $imgs=[];
        foreach($this->images as $img) {
        	$imgs[] = [
        		"id"        => $img->id,
        		"title"     => $img->title,
        		"caption"   => $img->caption,
        		"original"  => $img->picture->original->url,
        		"profile"   => $img->picture->profile->url,
        		"thumbnail" => $img->picture->thumbnail->url,
        	];
        }
        return $imgs;
    }
    /**
     * Links attached to the project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function links() {
        return $this->hasMany('Portfolio\ProjectLink');
    }
    /**
     * List items attached to the project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function listItems() {
        return $this->hasMany('Portfolio\ProjectListItem');
    }
    public function getListArrayAttribute() {
        $list=[];
        foreach($this->listItems as $item) {
            $list[] = $item->list_item;
        }
        return $list;
    }
    public function getLinkArrayAttribute() {
        $link=[];
        foreach($this->links as $item) {
            $link[] = [
                "title" => $item->title,
                "url"   => $item->url
            ];
        }
        return $link;
    }
    /**
     * Languages attached to this project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function lang() {
        return $this->skills->filter(function($skill)
            {
                if($skill->category_id <= 2)
                {
                    return $skill;
                }
         });
    }
    /**
     * Returns an array of Language names.
     * @return array
     */
    public function getLangArrayAttribute() {
        $lang=[];
        foreach($this->lang() as $item) {
            $lang[] = $item->name;
        }
        return $lang;
    }
    /**
     * Returns an array of Language names and ratings.
     * @return array
     */
    public function getLangRatingArrayAttribute() {
        $lang=[];
        // dd($this->lang());
        foreach($this->lang() as $item) {
            $lang[] = [
                "name"   => $item->name,
                "rating" => $item->rating
            ];
        }
        return $lang;
    }
    /**
     * Technologies attached to this project.
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function tech() {

        return $this->skills->filter(function($skill)
            {
                if($skill->category_id > 2)
                {
                    return $skill;
                }
         });
    }
    /**
     * Return an array of Technology names.
     * @return array
     */
    public function getTechArrayAttribute() {
        $tech=[];
        foreach($this->tech() as $item) {
            $tech[] = $item->name;
        }
        return $tech;
    }
    public function getTechRatingArrayAttribute() {
        $tech=[];
        foreach($this->tech() as $item) {
            $tech[] = [
                "name"   => $item->name,
                "rating" => $item->rating,
            ];
        }
        return $tech;
    }

    public function save(array $options = array()) {
        $this->resluggify();
        parent::save($options);
    }
}

app/ProjectType.php
<?php

namespace Portfolio;

use Illuminate\Database\Eloquent\Model;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use Portfolio\Project;


class ProjectType extends Model
{
	use SluggableTrait;
	
	public $timestamps = false;

	/**
     * Makes Project Type sluggable.
     * @var array
     */
    protected $sluggable = array(
        'build_from' => 'name',
        'save_to' => 'slug',
        'on_update' => true,
    );

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description',
    ];

    public function projects() {
        return $this->hasMany('Portfolio\Project');
    }

}

resources/views/edit/project/create.blade.php
@extends('layouts.app')

@section('title')
New Project
@endsection

@section('content')

<div class="container">
    <h2 class="container row">New Project</h2>
    <div class="panel panel-primary">
        <div class="panel-body">
            {{Form::open([
                "url"    => route('edit.project.store'),
                "method" => "POST",
                "files"=>true,
            ])}}
            @include('edit.project.form')
            {{Form::close()}}  
        </div>
    </div>
</div>
@endsection

resources/views/edit/project/edit.blade.php
@extends('layouts.app')

@section('title')
Edit {{$project->name}}
@endsection

@section('content')

<div class="container">
    <h2 class="container row">
    	Edit Project
    	<small>{{$project->name}}</small>
    </h2>
    <div class="panel panel-primary">
        <div class="panel-body">
            {{Form::model($project, [
                "url"    => route('edit.project.update', $project->slug),
                "method" => "PUT",
                "files"  => true,
            ])}}
            @include('edit.project.form')
            {{Form::close()}}  
        </div>
    </div>
</div>

</script>
@endsection

resources/views/edit/project/form-general.blade.php
<fieldset>
    <legend><span class="glyphicon glyphicon-pencil"></span> General Information</legend>
    <div class="form-group">
        <label for="project_type_id">Project Type</label>
        <select name="project_type_id" class="form-control">
            @foreach($projectTypes as $type)
            <option value="{{$type->id}}"
            @if($type->id === $project->project_type_id)
                selected
            @endif
            >{{$type->name}}
            </option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="name">Name</label>
        {!!Form::text('name', $project->name,["id"=>"name", "class"=>"form-control", "placeholder"=>"Enter a name for this project..."])!!}
    </div>

    <div class="form-group">
        <label for="name">Description</label>
        {!!Form::textarea('description', $project->description,["id"=>"description", "class"=>"form-control", "placeholder"=>"Describe the project...", "rows" => 5])!!}
    </div>
</fieldset>

resources/views/edit/project/form-images.blade.php
<fieldset>
    <legend><span class="glyphicon glyphicon-picture"></span> Screenshots</legend>
    {{-- Add Four Image Fieldsets --}}
    @foreach([0,1,2,3] as $a)
		<?php $b=$a+1;?>
		<div class="row zebra">
		    <div class="col-sm-6">
				{{-- Image Title  --}}
			    <div class="form-group">
			        <label for="imageTitles[{{$a}}]">Title {{ $b }}</label>
			        {!!Form::text("imageTitles[$a]",
			        	(isset($project->images[$a]) ? $project->images[$a]->title : ''), 
			        	[
			        		"id"=>"imageTitles[$a]", 
			        		"placeholder"=>"Image {$b} Title", 
			        		"class"=>"form-control", 
					])!!}
			    </div>
				{{-- Image Upload  --}}
			    <div class="form-group">
			        <label for="images[{{$a}}]">Image {{ $b }}</label>
			        {!!Form::file("images[$a]", [ "id" => "images[$a]"])!!}
			    </div>
		    </div>
		    {{-- Image Caption --}}
		    <div class="col-sm-6">
		        <label for="images[{{$a}}]">Caption {{ $b }}</label>
			    <div class="form-group ">
			        {!!Form::textarea("imageCaptions[$a]",
			        	(isset($project->images[$a]) ? $project->images[$a]->caption : ''),
			        	[
			        		"id"=>"imageCaptions[$a]",
			        		"rows" => 4 ,
			        		"placeholder"=>"Describe this screenshot...", 
			        		"class"=>"form-control", 
			        ])!!}
			    </div>
			</div>
			{{-- Current Image Display --}}
			@if(isset($project->images[$a]))
				<div class="col-xs-12">
					<figure class="text-center">
						<img src="{{$project->images[$a]->picture->medium->url}}" alt="Image {{$a}}" class="img img-responsive img-rounded">
					</figure>
					@if($a < 3)
						<button type="submit" class="btn btn-primary pull-right">Save Project</button>
					@endif
				</div>
				@endif
		</div>
   @endforeach
</fieldset>

resources/views/edit/project/form-items.blade.php
<fieldset>
    <legend><span class="glyphicon glyphicon-star"></span> Project Features</legend>
	@foreach([0,1,2,3] as $a)
	<div>
	    <div class="form-group">
	        <label for="name">Feature {{$a+1}}</label>
            {!!Form::text("listItem[$a]", 
            (isset($project->listItems[$a]) ? $project->listItems[$a]->list_item : ''),
            [
            	"class"       => "form-control", 
            	"placeholder" => "Key points about this project..."
           	])!!}
	    </div>
	</div>
    @endforeach
</fieldset>

resources/views/edit/project/form-links.blade.php
<fieldset>
    <legend><span class="glyphicon glyphicon-link"></span> Links</legend>
    @foreach([0,1,2] as $a)
        <div class="row">
            <div class="form-group col-sm-6">
            	<label for="linkTitle[{{$a}}]">Link {{$a + 1}} Title</label>
                {!!Form::text("linkTitle[$a]", 
                	(isset($project->links[$a]) ? $project->links[$a]->title : ''),
                	[
                		"id"          => "linkTitle[$a]", 
                		"class"       => "form-control", 
                		"placeholder" => "Enter a link title..."
                ])!!}
            </div>
            <div class="form-group col-sm-6">
            	<label for="linkUrl[{{$a}}]">Link {{$a + 1}} Url</label>
                {!!Form::text("linkUrl[$a]", 
                	(isset($project->links[$a]) ? $project->links[$a]->url : ''),
                	[
                		"id"          => "linkUrl[$a]", 
                		"class"       => "form-control", 
                		"placeholder" => "Add the URL..."
                ])!!}
            </div>
        </div>
    @endforeach
</fieldset>

resources/views/edit/project/form-skills.blade.php
<legend><span class="glyphicon glyphicon-briefcase"></span> Project Skills </legend>
<p class="lead">Add any skills which are applicable to this project.</p>

<div class="container row">
	<fieldset class="col-sm-3 col-xs-6 row">
	    <legend><span class="glyphicon glyphicon-book"></span> Lang</legend>

	    @foreach($langs as $lang)
		    <p><strong>{{$lang->name}}</strong></p>
		    @foreach($lang->skills as $skill)
			    <div class="checkbox">    
			        <label>
			            <input 
			                type="checkbox" 
			                name="lang[]" 
			                value={{$skill->slug}}
			            @if(in_array($skill->name, $project->langArray))
			                checked
			            @endif
			            > {{$skill->name}}
			        </label>
			    </div>
	    	@endforeach
	    @endforeach

	</fieldset>

	<fieldset class="col-sm-9 col-xs-6 container">
	    <legend><span class="glyphicon glyphicon-cog"></span> Tech</legend>
	    
	    @foreach($techs as $cat)
	    <div class="col-sm-4 row">
	        @if( count($cat["skills"]) )
	            <p><strong>{{$cat["name"]}}</strong></p>
		            @foreach($cat["skills"] as $tech)
		                <div class="checkbox">    
		                    <label>
		                        <input 
		                            type="checkbox" 
		                            name="tech[]" 
		                            value={{ $tech["slug"] }}
		                        @if( in_array($tech["name"], $project["techArray"]) )
		                            checked
		                        @endif
		                        > {{ $tech["name"] }}

		                    </label>
		                </div>
		            @endforeach
	        	@endif
	    	</div>
	    @endforeach
	</fieldset>
</div>

resources/views/edit/project/form.blade.php
<div>
	<ul class="nav nav-pills nav-justified" role="tablist">
		<li role="presentation" class="active">
			<a href="#info" aria-controls="info" role="tab" data-toggle="tab">
				<span class="glyphicon glyphicon-pencil"></span>	
				Info
			</a>
		</li>
		<li role="presentation">
			<a href="#features" aria-controls="features" role="tab" data-toggle="tab">
				<span class="glyphicon glyphicon-star"></span>	
				Features
			</a>
		</li>
		<li role="presentation">
			<a href="#links" aria-controls="links" role="tab" data-toggle="tab">
				<span class="glyphicon glyphicon-link"></span>
				Links
			</a>
		</li>
		<li role="presentation">
			<a href="#images" aria-controls="images" role="tab" data-toggle="tab">
				<span class="glyphicon glyphicon-picture"></span>
				Images
			</a>
		</li>
		<li role="presentation">
			<a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">
				Skills
				<span class="glyphicon glyphicon-briefcase"></span>	
			</a>
		</li>
	</ul>
	<br>

	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active in" id="info">
			@include('edit.project.form-general')
		</div>
		<div role="tabpanel" class="tab-pane fade" id="features">
			@include('edit.project.form-items')
		</div>
		<div role="tabpanel" class="tab-pane fade" id="links">
			@include('edit.project.form-links')
		</div>
		<div role="tabpanel" class="tab-pane fade" id="images">
			@include('edit.project.form-images')
		</div>
		<div role="tabpanel" class="tab-pane fade" id="skills">
			@include('edit.project.form-skills')
		</div>
	</div>

	<button type="submit" class="btn btn-primary pull-right">Save Project</button>

</div>

resources/views/edit/project/index.blade.php
@extends('layouts.app')

@section('title')
Projects
@endsection

@section('content')

<div class="container">
<h2 class="row">Projects</h2>
<ul class="nav nav-pills" role="tablist">
@foreach($projectTypes as $type)
<?php $class = ($type->id == 1 ? 'active' : ''); ?>

    <li role="presentation" class="{{$class}}">
    	<a href="#type-{{$type->id}}" aria-controls="type-{{$type->id}}" role="tab" data-toggle="tab">
    		{{$type->name}}
    	</a>
    </li>

@endforeach
</ul>

<br>
  <!-- Tab panes -->
<div class="tab-content">
@foreach($projectTypes as $type)
    <div role="tabpanel" class="tab-pane {!! ($type->id == 1 ? 'active' : '') !!}" id="type-{{$type->id}}">
		<div class="panel panel-primary">
		  <div class="panel-heading ">
	    	<h3>{{ $type->name }}</h3>
		  </div>
  		  <div class="panel-body">
			<p class="lead">{{$type->description}}</p>
		  </div>
			<table class="table table-responsive table-striped">
	            <thead>
	                <th class="col-xs-3">Name</th>
	                <th class="col-xs-7">Description</th>
	                <th class="col-xs-2">Actions</th>
	            </thead>
	            <tbody>
	                @foreach($type->projects as $project)
	                <tr>
	                    <td>
	                        {{ $project->name }}
	                    </td>
	                    <td>
	                        {{ $project->description }}
	                    </td>
	                    <td>
	                        <a href="{!! route('edit.project.edit', $project->slug)  !!}" type="button" class="btn btn-success" title="Edit Project: {{$project->name}}">
	                            <span class="glyphicon glyphicon-pencil"></span>
	                        </a>

	                        @include('partials.delete-project-form')
	                    </td>
	                </tr>
	                @endforeach
	            </tbody>
	        </table>
		</div>
	</div>
@endforeach
<a href="{!! route('edit.project.create') !!}" class="btn btn-block btn-primary btn-lg">
	<span class="glyphicon glyphicon-plus"></span> Add a New Project
</a>
</div>

@endsection